### ISSUE TITLE
Recarga Clarin

### ISSUE THREAD

**Issue by Diezi** [emilioastarita/ClarinSinPayWall#1]
Antes que nada, quería agradecer por la extensión en Chrome. El problema que detecto es que la misma se recarga continuamente cuando se navega en la misma.

**Comment by emilioastarita** [comment]
che no lo pude reproducir. Si navegas el sitio con las developers tools abiertas y el preserve log encendido ves algún error JS que te llame la atención?

**Comment by Diezi** [comment]
Solucionado, era un error mío de configuración del browser. Muchas gracias!!!
